### PR TITLE
Sanitize string to avoid XML format error

### PR DESCRIPTION
**Pull request by hissy**
Remove all invalid characters before loading XML file to avoid this error:

Screen Shot 2020-11-02 at 5 58 14

### CODE REVIEW

**Comment by mlocati** [comment]
I'm not sure that stripping out characters is the way to go. I'd instead correctly generate the xml file

**Comment by hissy** [comment]
You mean, it's better to strip characters for WordPress file only, right?

**Comment by mlocati** [comment]
Could you provide an example of a problematic XML file (or at least the problematic part of it)?

**Comment by hissy** [comment]
I can't share the XML file because it contains the content of my client, but I can share which characters are invalid for me.

https://unicode-table.com/en/001C/
https://unicode-table.com/en/001D/

I don't know why these characters exist in the export file, but maybe our client copied from MS Word or other text editors. Or maybe some WordPress plugin inserted it.

**Comment by mlocati** [comment]
Could you share an hex view of those problematic characters?

**Comment by hissy** [comment]
You can check it on unicode-table.com

**Comment by mlocati** [comment]
I asked because I wanted to be sure about the codes of thise two characters

**Comment by hissy** [comment]
@mlocati What do you mean by "codes"? You can check the hex code on that website.

**Comment by hissy** [comment]
I've updated the `ParserTrait` class to make it enable to import a large XML file

**Pull request merged**
